FROM node:22-alpine AS base
WORKDIR /repo
RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY web/package.json ./web/package.json

RUN pnpm -C /repo install --frozen-lockfile --filter ./web...

COPY web ./web
WORKDIR /repo/web
RUN pnpm build

FROM nginx:1.27-alpine AS runner
# envsubst is in gettext
RUN apk add --no-cache gettext

# template nginx + build
COPY web/nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=base /repo/web/dist /usr/share/nginx/html

EXPOSE 80
# Replace ${API_URL} at container start then run nginx
CMD ["/bin/sh", "-c", "envsubst '$$API_URL' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
